#:schema taplo://taplo.toml
# https://taplo.tamasfe.dev/configuration/file
include = [".taplo.toml", "hugo.toml", "theme.toml"]

[schema]
path = "https://json.schemastore.org/hugo.json"

[formatting]
# Formatter options: https://taplo.tamasfe.dev/configuration/formatter-options.html
align_comments = false
array_auto_collapse = false

[[rule]]
include = ["hugo.toml"]
[rule.schema]
path = "https://json.schemastore.org/hugo.json"

[[rule]]
include = ["theme.toml"]
[rule.schema]
path = "https://json.schemastore.org/hugo-theme.json"

[[rule]]
include = [".taplo.toml"]
[rule.schema]
path = "taplo://taplo.toml"
